### PR TITLE
fix: reload channel list when sort changed

### PR DESCRIPTION
**Pull request by giautm**
# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [ ] Code changes are tested (add some information if not applicable)

## Description of the pull request

Reference the implement in react-native package

https://github.com/GetStream/stream-chat-react-native/blob/04dbc9bf3e0f334215b6bac3221a8963951e97e2/package/src/components/ChannelList/hooks/usePaginatedChannels.ts#L126-L146

### CODE REVIEW

**Comment by giautm** [comment]
Hi @DanC5, can you review this PR please?

**Comment by vishalnarkhede** [comment]
@giautm we don't use objects directly in hook dependency!!

**Comment by giautm** [comment]
hi @vishalnarkhede, I switched to `sortString`

**Comment by giautm** [comment]
BTW, I saw the code was duplicated from `stream-chat-react` and `stream-chat-react-native`. Do you have any plan to put them into single packages (ex: stream-react-hooks)?

**Comment by vishalnarkhede** [comment]
> BTW, I saw the code was duplicated from `stream-chat-react` and `stream-chat-react-native`. Do you have any plan to put them into single packages (ex: stream-react-hooks)?

But maybe in near future, we might be looking into this - https://github.com/GetStream/stream-chat-react-native/discussions/501#discussion-2227864

**Review by vishalnarkhede — APPROVED** [review]

**Review by DanC5 — APPROVED** [review]
@giautm thanks for the contribution and it definitely makes sense to update the list on sort changes, similar to how we do for filters. I'll likely be making a release later today with this updated include, thanks!

**Pull request merged**
