### PR TITLE
fix: enable search results scrolling

### PR DESCRIPTION
**Pull request by MartinCupela**
### 🎯 Goal

Fix the bug in channel search results list to make it scrollable. If the channel search result list overflew the parent, it was not possible to scroll the list.

This fix depends on https://github.com/GetStream/stream-chat-css/pull/232

### CODE REVIEW

**Review by arnautov-anton — APPROVED** [review]

**Comment by ayushidianapps** [comment]
Team, your fix has created issues in our project.
The inline class has distorted the UI, I think this is not a good solution, you might need to add more conditions before giving classes.

**Comment by arnautov-anton** [comment]
Hey, @ayushidianapps, thank you for pointing this out - could you also share screenshots of the broken UI, please? @MartinCupela we should probably revisit this one.

**Comment by MartinCupela** [comment]
@ayushidianapps if I understood well, you have CSS rules for `inline` class and those rules now affect the element, that received this class in search component. Is that right? We should probably namespace this class to `str-chat__channel-search--inline`. Would that solve your problem?

**Comment by ayushidianapps** [comment]
Hi,
I am not sure that would solve our problem because that class would be
picked from the css automatically, right?

Is there any condition for you to have the inline class?

**Comment by MartinCupela** [comment]
@ayushidianapps CSS rules are applied based on classes associated with the elements. Could you please answer the following for us to better understand the problem:

> if I understood well, you have CSS rules for inline class and those rules now affect the element, that received this class in search component.

**Comment by ayushidianapps** [comment]
Yes the inline class had affected our CSS

**Comment by MartinCupela** [comment]
@ayushidianapps we have [released fix for this](https://github.com/GetStream/stream-chat-react/releases/tag/v10.8.7). The added class is now namespaced and should not be impacted by your `.inline` rule.

**Comment by ayushidianapps** [comment]
Awesome, thanks for the update!

**Pull request merged**
