### PR TITLE
feat: add optional renderChannels prop to ChannelList

### PR DESCRIPTION
**Pull request by rcdvl**
### 🎯 Goal

Our product has the requirement to show dynamic ChannelList sub-sections based on custom channel data (dynamic), which we could not find a way to do using the built-in props.
In order to achieve this we added a `renderChannels` optional prop that is a function to be called when rendering channels, instead of just looping through each channel showing its `ChannelPreview`.

### 🛠 Implementation details

When `renderChannels` prop is passed to `ChannelList` it's called during render instead of `loadedChannels.map(renderChannel)}`.

### 🎨 UI Changes

N/A

### CODE REVIEW

**Comment by MartinCupela** [comment]
@rcdvl thank you for the contribution. Could you please add more details about how your application behaves in order we can understand better your context? At the end, would your `renderChannels` function do something else than `channels.map`?

**Comment by rcdvl** [comment]
We have a separate ChannelList for each channel type ("team", "messaging", etc...) and inside these lists, we have collapsible sections based on some custom (and dynamic) channel data.
With the `renderChannels` prop we have access to all the channels before rendering the previews thus making it possible to group channels accordingly.

**Comment by MartinCupela** [comment]
@rcdvl thank you for the clarification. This makes sense. Could I ask you for providing the example you described for other users, in order they can imagine the possibilities? It would be a great value contribution. The example file could be added to `docusaurus/docs/React/custom-code-examples` folder. Thank you

**Review by arnautov-anton — APPROVED** [review]

**Review by petyosi — APPROVED** [review]

**Comment by arnautov-anton** [comment]
Thank you for your contribution, @rcdvl! Merging now, we'll release it with the few other little tweaks which are in the works soon. :)

**Comment by jaobrown** [comment]
Any ideas how to combine `renderChannels` with `ChannelList`'s `Preview` prop?

For example:
The following would allow us to provide props like `setActiveChannel`, `active`, `lastMessage`, etc into a custom Preview component:

```<ChannelList Preview={(props) => <MyComponent {...props} />}```


But the following is needed to use `renderChannels`:
```
const renderChannels: ChannelListProps['renderChannels'] = (
    loadedChannels,
  ) => {
    return loadedChannels.map((channel) => {
      const conversationData: ChannelPreviewContact =
        visitor?.userAccount?.conversations?.edges.find(
          (edge) => edge?.node?.streamChannelId === channel.id,
        )?.node;

      return (
        <ChannelPreview
          // need to get this from channel list
          // for example, setActiveChannel, active, lastMessage, etc
          {...props} // not sure where to get props from
          channel={channel}
          conversationData={conversationData}
          key={channel.id}
          onClick={() => onPreviewSelect(channel.id)}
        />
      );
    });
  };
```

But obviously `props` is not defined here—where can I get this from? **The main objective is to map some of our own application data into the preview component, to merge our application and stream into a component.**

**Comment by rcdvl** [comment]
> Any ideas how to combine `renderChannels` with `ChannelList`'s `Preview` prop?
> 
> For example: The following would allow us to provide props like `setActiveChannel`, `active`, `lastMessage`, etc into a custom Preview component:
> 
> ```js
> <ChannelList Preview={(props) => <MyComponent {...props} />}
> ```
> 
> But the following is needed to use `renderChannels`:
> 
> ```js
> const renderChannels: ChannelListProps['renderChannels'] = (
>     loadedChannels,
>   ) => {
>     return loadedChannels.map((channel) => {
>       const conversationData: ChannelPreviewContact =
>         visitor?.userAccount?.conversations?.edges.find(
>           (edge) => edge?.node?.streamChannelId === channel.id,
>         )?.node;
> 
>       return (
>         <ChannelPreview
>           // need to get this from channel list
>           // for example, setActiveChannel, active, lastMessage, etc
>           {...props} // not sure where to get props from
>           channel={channel}
>           conversationData={conversationData}
>           key={channel.id}
>           onClick={() => onPreviewSelect(channel.id)}
>         />
>       );
>     });
>   };
> ```
> 
> But obviously `props` is not defined here—where can I get this from? **The main objective is to map some of our own application data into the preview component, to merge our application and stream into a component.**

AFAIK `renderChannels` has a 2nd argument for the channel preview, so that you would have access to the `Preview` prop from the `ChannelList`. Is it what you need?

**Pull request merged**
