### PR TITLE
Fix special chars in file uploads

### PR DESCRIPTION
**Pull request by vishalnarkhede**
# Submit a pull request

## CLA

- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [ ] The code changes follow best practices
- [ ] Code changes are tested (add some information if not applicable)

## Description of the pull request
Regarding - https://getstream.zendesk.com/agent/tickets/1821

If you have some special chars in file name, then our api doesn't upload the image/file correctly. Adding a small check for ascii chars in filename will help this cause.  E.g., if you have korean chars in fileaname (which is quite possible if the user is from there)!!

### CODE REVIEW

**Comment by YohaanYoon** [comment]
@vishalnarkhede The branch is merged, but, I guess it does not have deployed. Could you explain the reason? Thanks

**Comment by YohaanYoon** [comment]
@vishalnarkhede This PR is not merged, but, it is closed. Could you explain the reason? 
Thanks :)

**Comment by YohaanYoon** [comment]
Please check this PR again. @vishalnarkhede @jaapbakker88

**Comment by vishalnarkhede** [comment]
Hey @YohaanYoon we decided not to go through with it. Instead we decided to add a prop function, which will let user override file upload request - `doFileUploadRequest`. 

In this function, you can call `props.channel.sendFile(file);` once you have modified the file name.

Let me know if you need s sample code.

**Comment by YohaanYoon** [comment]
@vishalnarkhede If you don't mind, give a sample code. 
Thanks in advance.

**Comment by vishalnarkhede** [comment]
@YohaanYoon  here you go

```
<MessageInput
    doFileUploadRequest={(file, channel) => {
        const modifedfile = validateAndChangeToCustomName(file);
        return channel.sendFile(modifedfile);
    }}
/>
```

Please check this for example of `validateAndChangeToCustomName` function - https://github.com/GetStream/stream-chat-react/pull/143/files#diff-7f911097ca1700d5671a7e9d257382dbR25

**Comment by YohaanYoon** [comment]
Thanks :)

**Pull request closed without merging**
