### PR TITLE
Feature/quoted message

### PR DESCRIPTION
**Pull request by DanC5**
# Submit a pull request

## CLA

- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [ ] The code changes follow best practices
- [ ] Code changes are tested (add some information if not applicable)

## Description of the pull request

Screen Shot 2021-05-05 at 3 04 55 PM

Screen Shot 2021-05-05 at 3 05 52 PM

### CODE REVIEW

**Review by ath92 — COMMENTED** [review]
I noticed some styling issues when quoting a message with a scraped URL in it:
image

**Comment by ath92** [comment]
When I try to reply to a message that only has an image in it (a .svg of the React logo), it seems to not render that attachment:
image

**Comment by ath92** [comment]
Not sure how easy it would be, but I'd personally like it if the message input textarea receives focus after I click "reply", so it's faster to start typing

**Comment by ath92** [comment]
image
If I start a thread based on a message that has a quoted message with an attachment, things look a little weird

**Comment by ath92** [comment]
Nit: I noticed that after pressing send, the value of the textarea is cleared, but the quoted message remains until the request has actually gone through (I think). Does it make sense to remove the quoted message a little earlier as well?

**Review by yetieaterxb1 — APPROVED** [review]
Grant quoted "LGTM"

**Pull request merged**
