### PR TITLE
Remove useMobilePress and useBreakpoint hooks

### PR DESCRIPTION
**Pull request by oliverlaz**
### 🎯 Goal

Remove useMobilePress and useBreakpoint hooks. Closes: #1641

### 🛠 Implementation details

**useMobilePress:**
Historically, this hook programmatically handled the user interaction with Message components by toggling `mobile-press` class upon user interaction. The goal of this operation was to have the message actions displayed on the screen.
Internally, we found a better solution by offloading this behavior to the browser and utilizing `:focus` and `:focus-within` CSS pseudo-selectors.

**useBreakpoint:**
This hook did hold the "programmatic" responsive UI breakpoints. We realized they aren't always in line with our stylesheet breakpoints and possibly with our customer's breakpoints. This misalignment was causing some inconsistencies and issues.
We are removing this hook because we believe defining UI breakpoints should be the responsibility of our customers.

**SearchResults:**
During the refactoring, we stumbled upon one side-effect where `popupResults` prop wasn't always respected. 
The fix of it could be a breaking change for a small percentage of our customers, but we believe this fix is the right thing to do.

### Related PRs:
- https://github.com/GetStream/stream-chat-css/pull/138
- https://github.com/GetStream/stream-chat-angular/pull/322

### CODE REVIEW

**Comment by szuperaz** [comment]
I think if it's a breaking change we should have a note in the commit message body https://github.com/semantic-release/semantic-release#commit-message-format

**Review by szuperaz — DISMISSED** [review]

**Comment by oliverlaz** [comment]
> > I think if it's a breaking change we should have a note in the commit message body https://github.com/semantic-release/semantic-release#commit-message-format
> 
> I agree, I can see that you have pretty sizable message in the first commit so you can extend it to contain `BREAKING CHANGE:` and you should be set. 👍

Sure thing! I'll update the commit message accordingly 👍

**Review by MartinCupela — APPROVED** [review]

**Review by petyosi — APPROVED** [review]

**Pull request merged**
